apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.backend.staticIP }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}      # 3000
      targetPort: {{ .Values.backend.containerPort }} # 3000
  selector:
    app: {{ .Chart.Name }}
    component: backend
