apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  loadBalancerIP: {{ .Values.backend.staticIP }}
  selector:
    app: {{ .Chart.Name }}
    component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}      # 3000
      targetPort: {{ .Values.backend.containerPort }} # 3000
