
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Chart.Name }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.containerPort | default 80 }}

          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js

          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | default "100m" | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | default "128Mi" | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | default "250m" | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | default "256Mi" | quote }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path | default "/" | quote }}
              port: {{ .Values.frontend.containerPort | default 80 }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds | default 10 }}

      volumes:
        - name: frontend-config
          configMap:
            name: {{ .Chart.Name }}-frontend-config
