apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mysql-init-sql
  labels:
    app: {{ .Chart.Name }}
    component: mysql
data:
  init.sql: |-
{{ .Files.Get "db/init.sql" | indent 4 }}
