# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Values.mysql.secretName | default "mysql-secret" }}
#   labels:
#     app: {{ .Chart.Name }}
#     component: mysql
# type: Opaque
# stringData:
#   mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName | default "mysql-secret" }}
type: Opaque
stringData:
  mysql-user: {{ .Values.mysql.user | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
